[package]
name = "rust_web_service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"

[dev-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
